version: '3.6'

services:
  user-service:
    build:
      context: './user'
      target: build
    command: ["sh", "-c", "make mod && cd ./cmd/server && realize start"]
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      TZ: Asia/Tokyo
    volumes:
      - "./user:/go/src/github.com/isy/grpc-sandbox/user"
  gateway:
    build:
      context: './gateway'
      target: build
    command: ["sh", "-c", "make mod && cd ./cmd/server && realize start"]
    ports:
      - "8081:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      TZ: Asia/Tokyo
    volumes:
      - "./gateway:/go/src/github.com/isy/grpc-sandbox/gateway"
  