version: '3.6'

services:
  user-service:
    build:
      context: './user'
      target: build
    command: ["sh", "-c", "make mod && cd ./cmd/server && realize start"]
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      TZ: Asia/Tokyo
    depends_on:
      - user-mysql
    volumes:
      - "./user:/go/src/github.com/isy/grpc-sandbox/user"
  user-mysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
  gateway:
    build:
      context: './gateway'
      target: build
    command: ["sh", "-c", "make mod && cd ./cmd/server && realize start"]
    ports:
      - "8081:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      TZ: Asia/Tokyo
    volumes:
      - "./gateway:/go/src/github.com/isy/grpc-sandbox/gateway"

volumes:
    mysql-data: