version: '3.6'

services:
  user-service:
    build:
      context: './user'
      target: build
    command: ["sh", "-c", "cd ./user && make mod && cd ./cmd/server && realize start"]
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      TZ: Asia/Tokyo
    volumes:
      - ".:/go/src/github.com/isy/grpc-sandbox/user"