#!/bin/bash

set -eu

cd $(dirname $0)

# Golang
if test ! $(which go)
then
  echo "Go could not be found. In order for this shell to work, you need Go"
  exit 1
else
  echo "go found."
fi

# Golang gRPC Library
if test ! $(which protoc-gen-go)
then
  echo "...Installing google.golang.org/grpc | protoc-gen-go"
  go get -u google.golang.org/grpc
  go get -u github.com/golang/protobuf/protoc-gen-go
else
  echo "protoc-gen-go found."
fi

# protobuf
if test ! $(which protoc)
then
  echo "...Installing protobuf"
  brew install protobuf
else
  echo "Protobuf found."
fi

# bufbuild/buf
if test ! $(which buf)
then
  echo "...Installing buf"
  brew tap bufbuild/buf
  brew install buf
else
  echo "buf found."
fi

# Genarated golang server *.pb.go
protoc \
  --proto_path=. \
  --go_out=plugins=grpc:../user/pb \
  --go_opt=paths=source_relative \
  user/*.proto


# Genarated golang gateway server *.pb.go
protoc \
  --proto_path=. \
  --go_out=plugins=grpc:../gateway/pb/ \
  --go_opt=paths=source_relative \
  user/*.proto