// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: payment/ios/ios.proto

package ios

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_payment_ios_ios_proto protoreflect.FileDescriptor

var file_payment_ios_ios_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6f, 0x73, 0x2f, 0x69, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x69, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6f, 0x73, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x58, 0x0a, 0x0a,
	0x49, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x3b, 0x69, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_payment_ios_ios_proto_goTypes = []interface{}{
	(*VerifyReceiptRequest)(nil), // 0: payment.ios.VerifyReceiptRequest
	(*empty.Empty)(nil),          // 1: google.protobuf.Empty
}
var file_payment_ios_ios_proto_depIdxs = []int32{
	0, // 0: payment.ios.IosService.VerifyReceipt:input_type -> payment.ios.VerifyReceiptRequest
	1, // 1: payment.ios.IosService.VerifyReceipt:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_ios_ios_proto_init() }
func file_payment_ios_ios_proto_init() {
	if File_payment_ios_ios_proto != nil {
		return
	}
	file_payment_ios_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_ios_ios_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_ios_ios_proto_goTypes,
		DependencyIndexes: file_payment_ios_ios_proto_depIdxs,
	}.Build()
	File_payment_ios_ios_proto = out.File
	file_payment_ios_ios_proto_rawDesc = nil
	file_payment_ios_ios_proto_goTypes = nil
	file_payment_ios_ios_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IosServiceClient is the client API for IosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IosServiceClient interface {
	VerifyReceipt(ctx context.Context, in *VerifyReceiptRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type iosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIosServiceClient(cc grpc.ClientConnInterface) IosServiceClient {
	return &iosServiceClient{cc}
}

func (c *iosServiceClient) VerifyReceipt(ctx context.Context, in *VerifyReceiptRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/payment.ios.IosService/VerifyReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IosServiceServer is the server API for IosService service.
type IosServiceServer interface {
	VerifyReceipt(context.Context, *VerifyReceiptRequest) (*empty.Empty, error)
}

// UnimplementedIosServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIosServiceServer struct {
}

func (*UnimplementedIosServiceServer) VerifyReceipt(context.Context, *VerifyReceiptRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyReceipt not implemented")
}

func RegisterIosServiceServer(s *grpc.Server, srv IosServiceServer) {
	s.RegisterService(&_IosService_serviceDesc, srv)
}

func _IosService_VerifyReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IosServiceServer).VerifyReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.ios.IosService/VerifyReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IosServiceServer).VerifyReceipt(ctx, req.(*VerifyReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IosService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.ios.IosService",
	HandlerType: (*IosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyReceipt",
			Handler:    _IosService_VerifyReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/ios/ios.proto",
}
